stages:
  - release

semantic-release:
  stage: release
  image: node:18-alpine
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - apk add --no-cache git
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
    - pnpm semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^[0-9]+(.([0-9]+|x))?.x$/
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "beta"
    - if: $CI_COMMIT_BRANCH == "alpha"
